<?php

function user_comment_alter_form_alter(&$form, &$form_state, $form_id, $author) {
    // print '<pre>';
    // print_r($form);
    // print '</pre>';
    if ($form['#form_id'] === 'comment_node_user_profile_comment_form') {
        // $form['rating'] = array
        //    (
        //        '#type' => textfield,
        //        '#title' => 'Rating out of 5',
        //        '#maxlength' => 1,
        //        '#access' => 1,
        //        '#weight' => -1,
        //    );
        if ($form['form_id']['#id'] != 'edit-comment-node-user-profile-comment-form') {
            if ($form['#node']->name === $form{'author'}['name']['#value']) {
                $form['#access'] = 0;
            }
        }
    //     $form['subject']['#access'] = 0;
    //     //OR
    //     //$form['subject']['#type'] = 'hidden';
    }
};
